// Code generated by mockery v2.38.0. DO NOT EDIT.

package mocks

import (
	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// API is an autogenerated mock type for the API type
type API struct {
	mock.Mock
}

// Metrics provides a mock function with given fields: w, r
func (_m *API) Metrics(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// RedirectURL provides a mock function with given fields: w, r
func (_m *API) RedirectURL(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// UrlShortner provides a mock function with given fields: w, r
func (_m *API) UrlShortner(w http.ResponseWriter, r *http.Request) {
	_m.Called(w, r)
}

// NewAPI creates a new instance of API. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *API {
	mock := &API{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
